bootJar {
    enabled = true
}

jar {
    enabled = false
}

dependencies {
    implementation project(':clients:client-kafka')
    implementation project(':core:core-enum')
    implementation project(':storage:db-mongo')
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
}