services:
  stt-server:
    image: seedege/stt-server:1.0.0
    container_name: stt-server
    ports:
      - "8000:8000"  # Server 1 포트
    environment:
      KAFKA_BROKER: kafka:9092  # Kafka 브로커 주소
      SERVER_NAME: stt-server
    networks:
      - docker_app-network

  llm-server:
    image: seedege/llm-server:1.0.0
    container_name: llm-server
    ports:
      - "8001:8001"  # Server 2 포트
    environment:
      KAFKA_BROKER: kafka:9092  # Kafka 브로커 주소
      SERVER_NAME: llm-server
    networks:
      - docker_app-network

#  server3:
#    image: your-server3-image:latest
#    container_name: server3
#    ports:
#      - "8003:8003"  # Server 3 포트
#    environment:
#      KAFKA_BROKER: kafka:9092  # Kafka 브로커 주소
#      SERVER_NAME: server3
#    networks:
#      - kafka-network

networks:
  docker_app-network:
    external: true
