package com.technote.core.enums;

public enum NoteStatus {
    NOT_EXIST,
    OUTLINE_GENERATING,
    COMMENTARY_EXPLANATION_GENERATING,
    COMMENTARY_FEEDBACK_GENERATING,
    COMMENTARY_GENERATING,
    COMPLETED;
}
